Update read-secrets-from-keyvault.yml

diff --git a/eng/pipelines/template/steps/read-secrets-from-keyvault.yml b/eng/pipelines/template/steps/read-secrets-from-keyvault.yml
--- a/eng/pipelines/template/steps/read-secrets-from-keyvault.yml
+++ b/eng/pipelines/template/steps/read-secrets-from-keyvault.yml
@@ -20,8 +20,18 @@ steps:
       displayName: Read key from Key Vault
       inputs:
         azureSubscription: 'azure-sdk-github-secrets'
-        scriptType: 'pscore'
+        scriptType: 'bash'
         scriptLocation: 'inlineScript'
         inlineScript: |
-          $secretValue = az keyvault secret show --name ${{ parameters.SecretName }} --vault-name ${{ parameters.KeyVaultName }} --query value --output tsv
-          echo "##vso[task.setvariable variable=${{ coalesce(parameters.OutputValueName, parameters.SecretName) }};issecret=true;]$secretValue"
+          for i in {1..5}; do
+            secret_value=$(az keyvault secret show --name ${{ parameters.SecretName }} --vault-name ${{ parameters.KeyVaultName }} --query value --output tsv)
+            if [[ -z "$secret_value" && $i -lt 5 ]]; then
+              echo "Failed to retrieve secret ${{ parameters.SecretName }} from ${{ parameters.KeyVaultName }}... Retrying after sleeping $i"
+              sleep $i
+            fi
+          done
+          if [[ -z "$secret_value" ]]; then
+            echo "Failed to retrieve secret ${{ parameters.SecretName }} from ${{ parameters.KeyVaultName }}"
+            exit 1
+          fi
+          echo "##vso[task.setvariable variable=${{ coalesce(parameters.OutputValueName, parameters.SecretName) }};issecret=true;]$secret_value"
